### ISSUE TITLE
How to be in IOS bound to the two port?

### ISSUE THREAD

**Issue by 958720320** [wouterverweirder/AIR-Mobile-UDP-Extension#10]
Hello, woute .First of all thank you for your great ANE . About your program AIR-Mobile UDP extension, ask how in the procedure of bind two port, make one of them as a send port, the other as a listening port?

Here we test, find your program can only bind to a port, used to send, cannot from another port to receive information. If you have a solution please must tell us, to disturb you, thank you!

**Comment by wouterverweirder** [comment]
I have just updated the library, this might be fixed. Will you let me know how it works for you now?
