### ISSUE TITLE
Using a lot of resources on android.

### ISSUE THREAD

**Issue by sirchad** [wouterverweirder/AIR-Mobile-UDP-Extension#15]
I am having a problem when I close the udpsocket like "udpSocket.close()". I can't ever call a new UDPSocket(). I have a ping button that someone can press but will not be used all that often. When running on android I can see the CPU usage is very high while the udpsocket is active. Any thoughts on how I can close the udpsocket while not in use and reopen it at various times?

I would like to add that this ane is critical and so glad you made this. I am not sure why this is not built-in to air, but thank you for stepping up.

**Comment by wouterverweirder** [comment]
This CPU usage is probably because of a non-blocking loop in my send thread. I'm looking into different alternatives for the Android part - seems like a lot of the android issues are related to the threading code I'm using.

**Comment by wouterverweirder** [comment]
I have committed a new version, which hopefully fixes the CPU usage issues on android.
