### ISSUE TITLE
crash on close()

### ISSUE THREAD

**Issue by 3urodud3** [wouterverweirder/AIR-Mobile-UDP-Extension#17]
Hello wouter,

I have a small issue with your very useful extension (btw thank you!)  I posted about this on your blog as well, and coincidentally, it relates to issue #16 just posted by perholmes.  In order to avoid any potential issue of unbinding such as they describe, what I am doing is reinstantiating my socket every time my app tries a send and receive over udp.

Even if instantiation fails due to an ongoing network outage, it is acceptable to me that the app will simply keep trying.  Eventually when the outage is resolved (e.g. WiFi becomes available), an instantiation will succeed, and communication will happen over the successfully bound socket.

But in order to bind to the same port as before when I reinstantiate, I must first close() the old socket.  The problem is that sometimes the close() call crashes my Android app.

Note that the crash is happening under normal operation, about once every three or four instantiations.  The available network interfaces are not changing, and so every time, the socket should definitely be healthy, bound and listening when close() is called.

Do you know of this issue, and do you have any suggestions?  Thanks in advance.

**Comment by sirchad** [comment]
This is what I was talking about in my issue #15 as well. I need to close the old socket because leaving it open causes 90% cpu usage, locks up the app. using close() will also lock up the app and make it stop responding.

**Comment by perholmes** [comment]
Hi,

I agree with this comment, I had the same issue. I tried to forcibly reinstantiate the socket any time the app was activated (and any time I got a NetworkChangeEvent from NetworkInfo), but I couldn't call close() and then open() for the reasons above.

Anyway, it's my impression that Wouter is on it, so let's see what happens!

Excellent extension, my app wouldn't be possible without it! Is it possible to donate to you Wouter? Is it allowed to ask this question on GitHub?

Best,

Per

**Comment by sirchad** [comment]
I did some looking around in the source code. It looks like on the android side of this ANE the close function calls itself and would go into an indefinite loop, thus causing android to see an app that is locked up and close it. My problem is that I do not know how to recompile an ANE as of yet. I will try to figure out how to do that.

**Comment by perholmes** [comment]
If that true, it sounds readily solvable.

**Comment by wouterverweirder** [comment]
close doesn't seem to call itself - uploaded updated version which seems to improve stability on android. My device does freeze when I turn off the wifi while the app is running. No idea why this happens, have to remove battery and reboot (entire thing is bricked).

Can you check if new version improves your scenario?

**Comment by perholmes** [comment]
Obviously it's critical for a production version that it can handle changes in the network environment. I would definitely expect that disabling WiFi kills the interface and thus any bound ports, so we need to figure out how to detect if a port has been force-closed before we use it.

Best,

Per

**Comment by wouterverweirder** [comment]
I have committed a new version for android. This should hopefully fix the CPU usage from #15 and does not freeze the phone when the wifi is turned off.
I will need to find a way to dispatch the close event / check bind status on android.

**Comment by perholmes** [comment]
Hi,

If the information is available and could feed an IsBound() function, then I really don't think you need to worry too much about events. You can detect on a timer if listening has ended, and you can check before sending if the port is open. I could totally work without an event if only the state is pollable.

Best,

Per

**Comment by wouterverweirder** [comment]
Problem with android is that you don't get exceptions on the datagramsocket code when wifi suddenly fails. This has been a bug for a while, which is in standard sockets as well (https://code.google.com/p/android/issues/detail?id=6144). Android will report that the socket is bound, even though your wifi has been closed / you are unable to receive messages.

**Comment by wouterverweirder** [comment]
Another update pushed, which should fix the original issue (close() crashing on Android).
Please comment on #16 concerning the "closed" event / isBound() functionality.

**Comment by 3urodud3** [comment]
Thanks wouter.  I have tested your latest version, and can confirm that it now works perfectly for the way I use the socket.  I have a timer handler which decides whether it needs to send/receive over udp.  If so, it first checks to see if a socket is already instantiated and bound, and in that case, calls close() before instantiating and binding a new socket.

I think that most applications could probably sidestep the need to monitor the status of the network interfaces if they do something similar.  It is udp after all, and data completeness/integrity issues, whatever their cause, typically must be handled by doing retries.  Such retries shouldn't care about any session state, unlike tcp, so a new socket is just as good as the old one for retrying.
