### ISSUE TITLE
UDPSocket cannot send on Android ICS

### ISSUE THREAD

**Issue by darkredz** [wouterverweirder/AIR-Mobile-UDP-Extension#3]
when use on android ICS it doesn’t seems to connect to the air server on desktop while it works on android 2.3. There’s no error too when debug with Flash builder with device connected. They are on the same wifi network.

Code:
                                var udpSocket:UDPSocket = new UDPSocket();
                var bytes:ByteArray = new ByteArray();
                var o:Object = {};
                o.command = "MESSAGE";
                o.content = "test...";
                bytes.writeObject(o);
                udpSocket.send(bytes, '192.168.1.6', 4321);

**Comment by benkuper** [comment]
Same issue here, tried with another app to be sure the reception is good, and udp packet are received when using another app on android (touchOSC).
Working on a Samsung Galaxy S3 on Android ICS 4.0.4

**Comment by wouterverweirder** [comment]
will look into this, might be fixed when I add support for broadcast reception of packets. I don't have access to a device with Android ICS, so have to rely on you guys to test if it works.

**Comment by benkuper** [comment]
I will be happy to help as soon as you get an update !

**Comment by benkuper** [comment]
got any update on how to fix this ? i can digg up the native android code if you explain a bit how this works.

**Comment by benkuper** [comment]
Ran some tests, receive() is working, got a working connection between pc and android, but the send() command doesn't do anything (i used a packet sniffer to be sure to get the packet if it reaches my computer)

**Comment by wouterverweirder** [comment]
thanks for the info. Will look into this after I finish some AIRKinect stuff.

**Comment by mente12** [comment]
Any idea when the broadcast will be available?

**Comment by wouterverweirder** [comment]
I just ran some tests, sending broadcast messages from the device does work. However I don't have an Android ICS device to do further testing, I'm stuck with an older droid2.

**Comment by mente12** [comment]
However, does the broadcast .255 work on IOS now?  Also, I can test on an Android if you are ready for testing.  I have an iPad and an Android Asus tablet. Plus iPhone and HTC phone.  Thanks.  

Sent from my HTC on the Now Network from Sprint!

----- Reply message -----
From: "wouterverweirder" reply@reply.github.com
Date: Thu, Jul 26, 2012 10:04 am
Subject: [AIR-Mobile-UDP-Extension] UDPSocket cannot send on Android ICS (#3)
To: "mente12" mente12@gmail.com

I just ran some tests, sending broadcast messages from the device does work. However I don't have an Android ICS device to do further testing, I'm stuck with an older droid2.

---

**Comment by wouterverweirder** [comment]
I've committed some changes, which might fix the ICS issues. Can't test it myself, so waiting for you guys to test it!

**Comment by sbleicker** [comment]
I will check this tomorrow!
