### ISSUE TITLE
Another port than the defined is used, payed project updates?

### ISSUE THREAD

**Issue by sbleicker** [wouterverweirder/AIR-Mobile-UDP-Extension#5]
Hi Wouter,

I love your work! This ANE is what i'm searching for months!
I hope I got the latest version, cause in the code-section, there are diffrent versions of the ane file.

The version I got now, is the one with iOS Broadcast working. But there are still some Problems:

The UDPPackets arn't send on the port defined in the bind method! I took a look with a network sniffer.
The UDPSocket was bound to port 1234 but it was send on port above 50000!

Another problem is that the response is not recieved by the client, maybe its a port problem also? The sniffer shows that the server sends a response packet - but the client did not recognize it (cause it is send to the ugly port >50000, maybe the client listens correctly on the defined port.

I need a full working ANE as soon as possible, so maybe i can pay you for bug-fixing? I could also send you a tablet with android ICS to complete your work for the android system.

Please contact me! 

Kind regards

Stefan

**Comment by wouterverweirder** [comment]
Hi Stefan,

The bind function sets the port where you listen for traffic, the destination of the package is specified with each send instruction.

If you are able to provide me a android ICS device, that should allow me to make sure everything works cross-platform. I do want to keep everything open source of course...

Feel free to send me an email at wouter@aboutme.be

Wouter

**Comment by sbleicker** [comment]
Hi Wouter,

my client is bound to port 1221 and sends a UDP Message to 255.255.255.255:11000.
Here is the the traffic captured by whireshark:

Internet Protocol Version 4, Src: 192.168.16.23 (192.168.16.23), Dst: 255.255.255.255 (255.255.255.255)
User Datagram Protocol, Src Port: 61614 (61614), Dst Port: irisa (11000)

So the server returns a message to the source IP (192.168.16.23) and the source port (61614).
But the UDP socket in the client is bound to port 1221 - so the return message can't be received.

The source port is changing every time - so, you listen on port defined by bind() - but the packet is leaving the client on a random port (I know that if not set a port, a random port is used. Maybe you listen on the defined port but not sending on it)

Hope it helps

Thanks
Stefan

**Comment by sbleicker** [comment]
Here is tho code (taken from your example):

protected function applicationCompleteHandler(event:FlexEvent):void
    {
        udpSocket = new UDPSocket();
        udpSocket.addEventListener(DatagramSocketDataEvent.DATA, udpDataHandler);
        udpSocket.bind(1221);
        udpSocket.receive();
    }

protected function sendClickHandler(event:MouseEvent):void
    {
        var bytes:ByteArray = new ByteArray();
        bytes.writeUTFBytes("NGBRAS-REQ");
        udpSocket.send(bytes, "255.255.255.255", 11000);
    }

Regards
Stefan

**Comment by wouterverweirder** [comment]
I've updated the extension for iOS. If you send udp packets from a udpsocket which is bound, the packets get sent from that port. This should fix your problem?

**Comment by sbleicker** [comment]
Yes, now it works wonderful for me!
Thank you for your fast help!

And don't forget to answer  my email ;)

Regads
Stefan

**Comment by wouterverweirder** [comment]
I've updated the Android part as well, and moved the sending code to a separate thread, which might fix the ICS sending issues. So... if somebody could test on ICS that would be great :)

**Comment by sbleicker** [comment]
I will check this tomorrow!

**Comment by sbleicker** [comment]
Sorry, running out of time...
Currently, the service i want to connect is in modification.
I wil check ICS when the new service is running.

Regards
Stefan

**Comment by sbleicker** [comment]
Hi,

not working. Here is the console output:
bind called on localAddress: 0.0.0.0
log bind called
log port: 1221 address: 0.0.0.0
log UDPListeningThread Constructor
log run method
log set timeout
log UDPSendingThread Constructor
error sendto failed: ENETUNREACH (Network is unreachable)

Regards
Stefan

**Comment by lovewqcm520** [comment]
I test today too, the same issue same log as sbleicker, on android 4.0.4.

Regards.

Jack.

**Comment by wouterverweirder** [comment]
it probably has something to do with ICS auto-selecting the wrong local IP address. I'll see if I can come up with a solution...

**Comment by wouterverweirder** [comment]
I've committed an update. Make sure to request the following permissions to your client app-xml:

```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
```

**Comment by lovewqcm520** [comment]
I just update your new repository, UDPClient looks work now on ICS. Here is the trace:

[SWF] be.aboutme.nativeExtensions.udp.UDPSocket - 4,327 bytes after decompression
[SWF] UDPClient.swf - 3,189,651 bytes after decompression
bind called on localAddress: 0.0.0.0
log bind on 192.168.1.154:1234
log UDPListeningThread Constructor
log run method
log set timeout
log UDPSendingThread Constructor

But I lauch my UDPServer(AIR Destop APP),  same port, didn't receive anything.

Regards.
Jack.

**Comment by lovewqcm520** [comment]
Sorry, It works, my mistake, I set the wrong server ip address.

Thanks for your updating,  wouterverweirder, very good job.

Regards.
Jack.

**Comment by sbleicker** [comment]
Well done! It's working on my Sony Tablet S with ICS!
Thank you!

Regards
Stefan
