### ISSUE TITLE
consecutive udpSocket.send() calls in a row causes error 

### ISSUE THREAD

**Issue by bmilesp** [wouterverweirder/AIR-Mobile-UDP-Extension#9]
I have a slider that needs to send a constant stream of udpSocket.send() calls. If i initialize UDPSocket() in the constructor, then udpSocket.send() on the sliders change event, ONLY THE FIRST CALL SUCCESSFULLY FIRES, all others after throw an error: 'error Invalid argument'.

i can work around this by initializing the UDPSocket() winthin the sliders change handler, but as you can imagine the slider's response is very slow and choppy  as it has to initialize hundreds of times a second.

**Comment by sbleicker** [comment]
Hi, where is the udpsocked.bind() used? In the constructor, or in the event handler?
I use the send command 3 times in one event (i have to send multicast UDP packages to 3 diffrent ports) - no problems.

The slider changes event is fired very often, maybe you should reduce th fireing. E.g. only fire if the slider value has changed his position for +-10px 

something like if (Math.abs(newpos-oldpos) > 10) UDPsocket.send();

Regards
Stefan

**Comment by bmilesp** [comment]
i'ved never got the bind working correctly as i thought that was only used
for receiving messages. I'll try and get that working first and i would
guess it goes in the constructor.

Thanks for taking the time to help me and great Native Extension! :)

-Brandon

**Comment by sbleicker** [comment]
Hi,

udpSocket.receive();    is to receive messages on defined port...

Here is a snippet of my script:
It fires 3 UDP packets 5 times with an delay of 1 second. 
You need the receive() if you expect an answer to your UDP packet.

```
    private var udpSocket:UDPSocket;
    private var fireTimeout:Timer;

    public function serviceFinder()
    {
        udpSocket = new UDPSocket();

        udpSocket.addEventListener(DatagramSocketDataEvent.DATA, udpDataHandler);
        udpSocket.bind(1221);
        udpSocket.receive();

        var bytes:ByteArray = new ByteArray();
        var packetData:String = "NGBRAS-REQ"; 
        bytes.writeUTFBytes(packetData);
        fireUDP(bytes);
    }



    private function fireUDP(packet:ByteArray):void{
        fireTimeout = new Timer(1000,5);
        fireTimeout.addEventListener(TimerEvent.TIMER, onFire);
        fireTimeout.start();

        function onFire(e:TimerEvent):void{
            udpSocket.send(packet, "255.255.255.255", 9514);    
            udpSocket.send(packet, "255.255.255.255", 8794);    
            udpSocket.send(packet, "255.255.255.255", 11000);
        }
    }

    private function udpDataHandler(event:DatagramSocketDataEvent):void
    { .... }
```

Hope it helps.

Regards

Stefan

**Comment by bmilesp** [comment]
great, thank you! -bp

**Comment by bmilesp** [comment]
worked like a charm! no need for the timer either! Thanks you so much! :)
